# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 09:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('classes', models.CharField(max_length=200)),
                ('exam', models.CharField(max_length=200)),
                ('marks', models.CharField(max_length=200)),
                ('dateconducted', models.DateField()),
                ('dateuploaded', models.DateField(auto_now=True)),
                ('answerpapers', models.FileField(upload_to='uncorrected/')),
            ],
        ),
        migrations.CreateModel(
            name='chats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('sender', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ExamDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('studentid', models.CharField(max_length=200)),
                ('classes', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='examdetails',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.StudentsList'),
        ),
        migrations.AddField(
            model_name='examdetails',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chats',
            name='studentuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieve_message', to='teacher.StudentsList'),
        ),
        migrations.AddField(
            model_name='chats',
            name='teacheruser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answersheets',
            name='students',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.StudentsList'),
        ),
        migrations.AddField(
            model_name='answersheets',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
